language: node_js
node_js: node
sudo: required
script:
- npm run lint
- npm run test:unit
- npm run test:bundle
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then npm run test:sauce; fi'
after_success: npm run report-coverage
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - node_modules
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  # SAUCE_ACCESS_KEY
  - secure: cpu4DdXddutV8VXGwkCiR99jiUwsGiUMshbMhceNJJ7LAjrZCSe9y8uMVIAIwGOjm3Qh8I4arjQjPSdQB9AqsnfpNso1mqMOfoGe4bc9TktnlC24RTE19qemtU42yqt9ktxnPojH0+4/V7u0b4fmbbKzXVMpXt7pt+oB1t7fY7r5cSci7gjTeiajccRRceOs2GD9p/MHiGaW/IP7yqj0QqLFyhGFaP+3mY2VFIL2rBGo/kOvSuRwkM5ACJVSxy1zGTombWRjVBGTqWM6vPiJbCHoBR7hSGwm09V4olic7tzJam5ozKy/UfhDGMihkZsRPsdF/TjZHjxdRr3Uwd/GU6L9BDYbG5fw7YMoMQyKxjEJT1FnO5vTBrQmvZvR4WTG8TJ3gyJTmxvuu2S3zsBQVhdMHfXcmnglrc2hOFWAay/yF/ReKVa5+KiD58pRmfbvI/Szd6UIDKECX/8JlbNxFH+zTyvTuJ3oLcXQZUXNGMTLZPofFvOPLZG5gu1Jt2Op9RG3oZ4RlTZXXuBbAdtlihFJdHo6EMHxbDThiKMb7ZJZSH0bBsW2KgorPM/ES4pNOFv/5U5ZhyEza+rDUWXq68s6rnqVsQfeAb4/dil7ZNpXF/JjM45TkgaBdAuSUKtvJNdmY9OiZviKrXhSHKYEsgXDPeosIeShtH0gkHNDtzk=
